var styles = {
	header:{
		"height":"1rem",
		"width":"100%",
		"background":"#b60005",
		"display":"flex",
		"justifyContent":"center",
		"alignItems":"center"
	},
	himg:{
		"width":"20%"
	},
	inputBox:{
		"width":"70%",
		"height":".6rem",
		"display":"flex",
		"justifyContent":"center",
		"alignItems":"center",
		"background":"#fff",
		"borderRadius":".15rem"
	},
	input:{
		"border":"0",
		"height":".5rem",
		"marginRight":".8rem"
	},
	footer:{
		"width":"100%",
		"height":"1rem",
		"position":"fixed",
		"bottom":"0",
		"left":"0",
		"background":"#f4f6f8",
		"display":"flex",
		"justifyContent":"center",
		"alignItems":"center"
	},
	footerDiv:{
		"width":"25%",
		"textAlign":"center"
	},
	bannerimg:{
		"width":"100%"
	},
	mainbox:{
		"display":"flex",
		"justifyContent":"center",
		"alignItems":"center"
	},
	mainimg:{
		"width":"25%",
		"fontSize":"12px",
		"display":"flex",
		"justifyContent":"center",
		"alignItems":"center",
		"flexDirection":"column"
	},
	imgs:{
		"width":"100%",
		"display":"block"
	},
	scrollbox:{
		"display":"flex",
		"justifyContent":"flex-start",
		"alignItems":"center",
		"marginTop":".15rem"
	},
	scroll:{
		"width":"20%"
	},
	bx:{
		"marginBottom":"0.2rem"
	},
	bgbox:{
		"display":"flex",
		"marginBottom":"0.2rem"
	},
	big:{
		"width":"50%"
	},
	bigright:{
		"width":"50%",
		"display":"flex",
		"justifyContent":"center",
		"alignItems":"center",
		"flexDirection":"column"
	},
	bjgimg:{
		"width":"100%",
		"display":"inline-block"
	},
	listbox:{
		"display":"flex",
		"width":"100%",
		"flexWrap":"wrap"
	},
	listimg:{
		"width":"98%"
	},
	list:{
		"width":"50%",
		"marginBottom":".1rem"
	},
	txtcolor:{
		"color":"#f10"
	},
	txt:{
		"display":"flex",
		"justifyContent":"space-between",
		"alignItems":"center"
	},
	ico:{
		"color":"#fff",
		"display":"inline-block",
		"width":".5rem",
		"height":".5rem",
		"textAlign":"center",
		"lineHeight":".5rem",
		"borderRadius":"50%",
		"background":"#f10",
		"marginRight":".2rem"
	}
}